version: '3.8'
services:
  postgres:
    image: 'juliansantosinfo/totvs_postgres:12.1.2510'
    container_name: totvs_postgres
    user: root
    restart: always
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      TZ: '${TZ}'
    volumes:
      - 'totvs_postgres_data:/var/lib/postgresql/data'
    networks:
      - totvs
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres'
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

  licenseserver:
    image: 'juliansantosinfo/totvs_licenseserver:3.7.0'
    container_name: totvs_licenseserver
    restart: always
    ports:
      - '28020:8020'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      LICENSE_TCP_PORT: '${LICENSE_TCP_PORT}'
      LICENSE_CONSOLEFILE: '${LICENSE_CONSOLEFILE}'
      LICENSE_PORT: '${LICENSE_PORT}'
      LICENSE_WEBAPP_PORT: '${LICENSE_WEBAPP_PORT}'
      TZ: '${TZ}'
    volumes:
      - 'totvs_licenseserver_data:/totvs/licenseserver'
    networks:
      - totvs

  dbaccess:
    image: 'juliansantosinfo/totvs_dbaccess:24.1.1.0'
    container_name: totvs_dbaccess
    restart: always
    ports:
      - '27890:7890'
    environment:
      DATABASE_PROFILE: POSTGRES
      DATABASE_SERVER: postgres
      DATABASE_PORT: 5432
      DATABASE_ALIAS: protheus
      DATABASE_NAME: protheus
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DBACCESS_LICENSE_SERVER: licenseserver
      DBACCESS_LICENSE_PORT: 5555
      DBACCESS_CONSOLEFILE: /totvs/dbaccess/multi/dbconsole.log
      TZ: '${TZ}'
    networks:
      - totvs

  appserver:
    image: 'juliansantosinfo/totvs_appserver:12.1.2510'
    container_name: totvs_appserver
    restart: always
    ports:
      - '25001:25001'
      - '25002:25002'
      - '25080:25080'
      - '25088:25088'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      APPSERVER_MODE: application
      APPSERVER_RPO_CUSTOM: /totvs/protheus/apo/custom.rpo
      APPSERVER_DBACCESS_DATABASE: POSTGRES
      APPSERVER_DBACCESS_SERVER: dbaccess
      APPSERVER_DBACCESS_PORT: 7890
      APPSERVER_DBACCESS_ALIAS: '${DATABASE_ALIAS}'
      APPSERVER_CONSOLEFILE: /totvs/protheus/bin/appserver/appserver.log
      APPSERVER_MULTIPROTOCOLPORTSECURE: 0
      APPSERVER_MULTIPROTOCOLPORT: 1
      APPSERVER_LICENSE_SERVER: licenseserver
      APPSERVER_LICENSE_PORT: '${LICENSE_PORT}'
      APPSERVER_PORT: 25001
      APPSERVER_WEB_PORT: 25002
      APPSERVER_REST_PORT: 25080
      APPSERVER_WEB_MANAGER: 25088
      EXTRACT_RESOURCES: 'true'
      TZ: '${TZ}'
    volumes:
      - 'totvs_appserver_data:/totvs/protheus'
    networks:
      - totvs
    depends_on:
      - licenseserver
      - dbaccess

  apprest:
    image: 'juliansantosinfo/totvs_appserver:12.1.2510'
    container_name: totvs_apprest
    restart: always
    ports:
      - '25101:25101'
      - '25102:25102'
      - '25180:25180'
      - '25188:25188'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      APPSERVER_MODE: rest
      APPSERVER_RPO_CUSTOM: /totvs/protheus/apo/custom.rpo
      APPSERVER_DBACCESS_DATABASE: POSTGRES
      APPSERVER_DBACCESS_SERVER: dbaccess
      APPSERVER_DBACCESS_PORT: 7890
      APPSERVER_DBACCESS_ALIAS: '${DATABASE_ALIAS}'
      APPSERVER_CONSOLEFILE: /totvs/protheus/bin/appserver/appserver.log
      APPSERVER_MULTIPROTOCOLPORTSECURE: 0
      APPSERVER_MULTIPROTOCOLPORT: 1
      APPSERVER_LICENSE_SERVER: licenseserver
      APPSERVER_LICENSE_PORT: '${LICENSE_PORT}'
      APPSERVER_PORT: 25101
      APPSERVER_WEB_PORT: 25102
      APPSERVER_REST_PORT: 25180
      APPSERVER_WEB_MANAGER: 25188
      EXTRACT_RESOURCES: 'true'
      TZ: '${TZ}'
    volumes:
      - 'totvs_appserver_rest_data:/totvs/protheus'
    networks:
      - totvs
    depends_on:
      - licenseserver
      - dbaccess

volumes:
  totvs_postgres_data:
    driver: local
  totvs_licenseserver_data:
    driver: local
  totvs_appserver_data:
    driver: local
  totvs_appserver_rest_data:
    driver: local

networks:
  totvs:
    driver: bridge
